CREATE TABLE baseball (
	date VARCHAR,
	number_of_games INT,
	day_of_week VARCHAR,
	v_name VARCHAR,
	v_league VARCHAR,
	v_game_number INT,
	h_name VARCHAR,
	h_league VARCHAR,
	h_game_number INT,
	v_score INT,
	h_score INT,
